version: "3.1.1"

services:
  mysql:
    container_name: mysql
    image: mysql:8
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: --innodb-redo-log-capacity=10485760
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  app:
    depends_on:
      - mysql
    image: car_sharing
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
        "spring.jpa.hibernate.ddl-auto" : "validate",
        "spring.jpa.show-sql" : "true",
        "jwt.expiration" : "$JWT_EXPIRATION",
        "jwt.secret" : "$JWT_SECRET",
        "bot.name" : "$BOT_NAME",
        "bot.key" : "$BOT_KEY",
        "stripe.public.key" : "$STRIPE_PUBLIC_KEY",
        "stripe.secret.key" : "$STRIPE_SECRET_KEY",
        "stripe.success.url" : "http://localhost:$SPRING_LOCAL_PORT/payments/success?session_id={CHECKOUT_SESSION_ID}",
        "stripe.cancel.url" : "http://localhost:$SPRING_LOCAL_PORT/payments/cancel?session_id={CHECKOUT_SESSION_ID}"
        }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
